### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#105]
`[20:51:15 WARN]: [Factions] Task #571 for Factions v1.6.9.5-U0.2.1-RC-1.6-RC generated an exception
java.lang.NullPointerException
        at com.massivecraft.factions.zcore.persist.MemoryFPlayer.checkIfNearbyEnemies(MemoryFPlayer.java:1047) ~[Factions-2019-02-20--02-12.jar:?]
        at com.massivecraft.factions.util.UtilFly$1.run(UtilFly.java:34) ~[Factions-2019-02-20--02-12.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-TacoSpigot-1be69cbf]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paper.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [paper.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper.jar:git-TacoSpigot-1be69cbf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by Driftay** [comment]
> `[20:51:15 WARN]: [Factions] Task #571 for Factions v1.6.9.5-U0.2.1-RC-1.6-RC generated an exception java.lang.NullPointerException at com.massivecraft.factions.zcore.persist.MemoryFPlayer.checkIfNearbyEnemies(MemoryFPlayer.java:1047) ~[Factions-2019-02-20--02-12.jar:?] at com.massivecraft.factions.util.UtilFly$1.run(UtilFly.java:34) ~[Factions-2019-02-20--02-12.jar:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-TacoSpigot-1be69cbf] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paper.jar:git-TacoSpigot-1be69cbf] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [paper.jar:git-TacoSpigot-1be69cbf] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-TacoSpigot-1be69cbf] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper.jar:git-TacoSpigot-1be69cbf] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper.jar:git-TacoSpigot-1be69cbf] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

fixed
