### ISSUE TITLE
ExceptionInInitializerError on Enable

### ISSUE THREAD

**Issue by JustCallMeHims** [ProSavage/SavageFactions#116]
This always happens when the plugin enables..
**defaultFactionPermissions = null in Conf.java**

` Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC (Is it up to date?)
java.lang.ExceptionInInitializerError
        at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:98) ~[?:?]
        at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.Conf.<clinit>(Conf.java:444) ~[?:?]
        ... 13 more`

**Comment by Driftay** [comment]
> This always happens when the plugin enables..
> **defaultFactionPermissions = null in Conf.java**
> 
> ` Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC (Is it up to date?) java.lang.ExceptionInInitializerError at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:98) ~[?:?] at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:151) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] Caused by: java.lang.NullPointerException at com.massivecraft.factions.Conf.<clinit>(Conf.java:444) ~[?:?] ... 13 more`

Fixed in Latest Update Located at: https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar
