### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by AlikSondor** [ProSavage/SavageFactions#118]
Log:
Startup / Reboot:
(Log with and to errors associated with SavageFactions)

```
[16:09:54 INFO]: [Factions] Enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC
[16:09:54 INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] ==== Setup ====
[16:09:54 INFO]: File was not found for players.json, assuming there is no need to migrate old players.json file.
[16:09:54 INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] ==== End Setup ====
[16:09:54 INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] === ENABLE START ===
[16:09:54 ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:98) ~[?:?]
        at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:150) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:745) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.Conf.<clinit>(Conf.java:444) ~[?:?]
        ... 18 more
[16:09:54 INFO]: [CreeperHeal] Enabling CreeperHeal v7.0.4
[16:09:54 INFO]: debug: false
[16:09:54 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.15.0.1
[16:09:54 INFO]: [PrisonMines] Enabling PrisonMines v3.1
[16:09:54 INFO]: [PrisonMines] HolographicDisplays was found
[16:09:54 INFO]: [PrisonMines] Loaded 1 mine(s)
[16:09:54 INFO]: [ReActions] Enabling ReActions v0.11.1
[16:09:54 INFO]: [ReActions] PlayEffect plugin is not found at your system
[16:09:54 INFO]: [ReActions] If you need more effects please download PlayEffect from:
[16:09:54 INFO]: [ReActions] http://dev.bukkit.org/bukkit-plugins/playeffect/
[16:09:54 INFO]: [ReActions] ProtocolLib connected
[16:09:54 INFO]: [ReActions] WorldGuard 6.2.2-SNAPSHOT; found. Bridge loaded: WGBridge 0.0.2/WG6x
[16:09:54 INFO]: [ReActions] Vault connected
[16:09:54 INFO]: [ReActions] Failed to load delayed actions
[16:09:54 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:09:54 INFO]: CONSOLE: Reload complete.
[16:09:55 INFO]: (FAWE) Plugin 'WorldGuard' found. Using it now.
[16:09:55 WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/BoardColl
[16:09:55 WARN]:        at com.boydti.fawe.bukkit.regions.FactionsFeature.<init>(FactionsFeature.java:23)
[16:09:55 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getMaskManagers(FaweBukkit.java:516)
[16:09:55 WARN]:        at com.boydti.fawe.Fawe.lambda$new$1(Fawe.java:282)
[16:09:55 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:09:55 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[16:09:55 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[16:09:55 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[16:09:55 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[16:09:55 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[16:09:55 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:09:55 WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.BoardColl
[16:09:55 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[16:09:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[16:09:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:09:55 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[16:09:55 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[16:09:55 WARN]:        ... 10 more
```

Use command /f:

`[16:11:11 INFO]: GreenChester issued server command: /f
[16:11:11 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Factions v1.6.9.5-U0.2.1-RC-1.6-RC
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1377) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.massivecraft.factions.Conf
        at com.massivecraft.factions.listeners.FactionsPlayerListener.preventCommand(FactionsPlayerListener.java:375) ~[?:?]
        at com.massivecraft.factions.zcore.MPluginSecretPlayerListener.onPlayerCommandPreprocess(MPluginSecretPlayerListener.java:23) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        ... 16 more
[16:11:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.1-RC-1.6-RC
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.massivecraft.factions.Conf
        at com.massivecraft.factions.listeners.FactionsPlayerListener.preventCommand(FactionsPlayerListener.java:375) ~[?:?]
        at com.massivecraft.factions.SavageFactions.handleCommand(SavageFactions.java:526) ~[?:?]
        at com.massivecraft.factions.SavageFactions.onCommand(SavageFactions.java:532) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        ... 15 more`

Server Version = spigot 1.12

**Comment by prosavage** [comment]
We fixed this, in https://github.com/ProSavage/SavageFactions/commit/e4899e4d8d78702fb8a3d224864686c92e7ff465 you can get a bleeding edge build from ci.prosavage.net , login as guest.
