### ISSUE TITLE
loading bug

### ISSUE THREAD

**Issue by call911nowplz** [ProSavage/SavageFactions#121]
The plugin does not load after the server startup. But using plugman, I can reload it in-game and it works. This is the error on startup.

> [14:56:41 INFO]: [Factions] Enabling Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE
> [14:56:41 INFO]: [Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE] ==== Setup ====
> [14:56:41 INFO]: [Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE] Minecraft Version 1.8 found, Title Fadeouttime etc will not be configurable.
> [14:56:41 INFO]: File was not found for players.json, assuming there is no need to migrate old players.json file.
> [14:56:41 INFO]: [Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE] === ENABLE START ===
> [14:56:41 ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.massivecraft.factions.Conf
at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:98) ~[?:?]
at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:150) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> [14:56:41 INFO]: [Factions] Disabling Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE
> [14:56:41 INFO]: [Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE] Disabled

**Comment by call911nowplz** [comment]
Update: The issue is still there even after using the version from http://ci.prosavage.net/

**Comment by call911nowplz** [comment]
Update 2: The problem was fixed after removing one of my plugins which was called zTotem. That's the link to the resource:
https://www.spigotmc.org/resources/%E2%98%86-ztotem-%E2%98%86-%C2%A4-faction-factionuuid-and-more-%E2%99%A7-1-8-1-13-%E2%99%A7-%C2%A4-config-yml-top-10-%C2%A4.47318/

**Comment by Driftay** [comment]
> Update 2: The problem was fixed after removing one of my plugins which was called zTotem. That's the link to the resource:
> https://www.spigotmc.org/resources/%E2%98%86-ztotem-%E2%98%86-%C2%A4-faction-factionuuid-and-more-%E2%99%A7-1-8-1-13-%E2%99%A7-%C2%A4-config-yml-top-10-%C2%A4.47318/

Update to the latest release here:

Was Fixed.

Link: https://jenkins.prosavage.net/job/SavageFactions/134/artifact/target/Factions-2019-03-11--07-30.jar
