### ISSUE TITLE
Error Plugin getting disabled.

### ISSUE THREAD

**Issue by MyConfiq** [ProSavage/SavageFactions#123]
[21:58:19] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC
[21:58:19] [Server thread/INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] ==== Setup ====
[21:58:19] [Server thread/INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] Minecraft Version 1.8 found, Title Fadeouttime etc will not be configurable.
[21:58:19] [Server thread/INFO]: File was not found for players.json, assuming there is no need to migrate old players.json file.
[21:58:19] [Server thread/INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] ==== End Setup ====
[21:58:19] [Server thread/INFO]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-RC] === ENABLE START ===
[21:58:19] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.6-RC (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:98) ~[?:?]
	at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:150) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.Conf.<clinit>(Conf.java:444) ~[?:?]
	... 13 more

**Comment by SvenjaReissaus** [comment]
Would you mind provided the Issue format on it's completeness?

**Comment by SvenjaReissaus** [comment]
Also Essentials and PlaceholderAPI are required dependencies if I can remember

**Comment by MyConfiq** [comment]
I got both essentials and placeholderAPI installed, 
and thats the only issue I get, the plugin won't enable

**Comment by SvenjaReissaus** [comment]
Please considering fulfilling the issue format, otherwise I will most likely not able to help you

**Comment by SvenjaReissaus** [comment]
Format was not provided on it's fullness, no actions will be taken since we cannot understand the problem.
