### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by SimplyHate** [ProSavage/SavageFactions#125]
[Factions] Task #75 for Factions v1.6.9.5-U0.2.1-RC-1.6-RC generated an exception

java.lang.NullPointerException

at com.massivecraft.factions.zcore.persist.MemoryFPlayer.checkIfNearbyEnemies(MemoryFPlayer.java:1047) ~[?:?]

at com.massivecraft.factions.util.UtilFly.lambda$run$0(UtilFly.java:26) ~[?:?]

at com.massivecraft.factions.util.UtilFly$$Lambda$60.000000000CF79470.run(Unknown Source) ~[?:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

**Comment by SimplyHate** [comment]
fixed
