### ISSUE TITLE
/f perms throws EventException - "Could not pass InventoryClickEvent"

### ISSUE THREAD

**Issue by Benlewis9000** [ProSavage/SavageFactions#184]
**Describe the bug**
When players use /f perms, the GUI to select the rule opens, but attempting to click a group it throws an EventExcept

**To Reproduce**
1. /f perms
2. Click any GUI item

**Expected behavior**
It should open the permission menu as normal for the selected group.

**Console error**
```
[23:02:26 WARN]: [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA] Invalid material for dummy item: 0
[23:02:26 ERROR]: Could not pass event InventoryClickEvent to Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: No enum constant com.massivecraft.factions.util.XMaterial.MemorySection[path='fperm-gui.action.materials', root='YamlConfiguration']
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
        at com.massivecraft.factions.util.XMaterial.valueOf(XMaterial.java:55) ~[?:?]
        at com.massivecraft.factions.zcore.fperms.PermissableAction.buildItem(PermissableAction.java:110) ~[?:?]
        at com.massivecraft.factions.zcore.fperms.gui.PermissableActionGUI.buildItems(PermissableActionGUI.java:162) ~[?:?]
        at com.massivecraft.factions.zcore.fperms.gui.PermissableActionGUI.build(PermissableActionGUI.java:110) ~[?:?]
        at com.massivecraft.factions.zcore.fperms.gui.PermissableRelationGUI.onClick(PermissableRelationGUI.java:93) ~[?:?]
        at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteractGUI(FactionsPlayerListener.java:884) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 16 more
```

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA

**Comment by Savag3life** [comment]
Did you change the config? The error is from your config, not the plugin. `'fperm-gui.action.materials'` the config location. Try resetting your config.yml files.

**Comment by Benlewis9000** [comment]
Nothing in that area was altered. I reinstalled the v2.2 released on Spigot and the issue seems to be gone. Not sure whether it was a restart or jar change that fixed it.
