### ISSUE TITLE
error in the console when place warbanner

### ISSUE THREAD

**Issue by ghost** [ProSavage/SavageFactions#189]
**Describe the bug**
when I place war banner there are errors about particle spam in the console.

**To Reproduce**
use war banner.

**Expected behavior**
no error

**Error**
```
[Factions] Task #6606 for Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA generated an exception
com.massivecraft.factions.util.Particles.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
at com.massivecraft.factions.util.Particles.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1409) ~[?:?]
at com.massivecraft.factions.util.Particles.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1340) ~[?:?]
at com.massivecraft.factions.util.Particles.ParticleEffect.display(ParticleEffect.java:572) ~[?:?]
at com.massivecraft.factions.listeners.FactionsBlockListener$1.run(FactionsBlockListener.java:415) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EnumParticle
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_131]
at com.massivecraft.factions.util.Particles.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:424) ~[?:?]
at com.massivecraft.factions.util.Particles.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1399) ~[?:?]
... 10 more
```

**Server VErsion (please complete the following information):**
 - Spigot Version: [Paper 1.14.3 -131]
 - Factions Version [Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.2-BETA]
 - Minecraft Version: [1.14.3]

**Comment by ElapsedDev** [comment]
As of right now, we will be adding a stable 1.14 Particle Effects
