### ISSUE TITLE
Spamming my console with this bug?

### ISSUE THREAD

**Issue by ZoneRaids** [ProSavage/SavageFactions#227]
[13:19:22 WARN]: [Factions] Task #254 for Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-4 generated an exception
java.lang.NullPointerException
at com.massivecraft.factions.integration.Essentials.isVanished(Essentials.java:50) ~[?:?]
at com.massivecraft.factions.zcore.persist.MemoryFPlayer.isVanished(MemoryFPlayer.java:304) ~[?:?]
at com.massivecraft.factions.zcore.persist.MemoryFPlayer.checkIfNearbyEnemies(MemoryFPlayer.java:1106) ~[?:?]
at com.massivecraft.factions.zcore.ffly.UtilFly.lambda$run$0(UtilFly.java:20) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Expected behavior**

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8
 - Factions Version Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-4
 - Minecraft Version: ?

**Additional context**

**Comment by Savag3life** [comment]
This issue has been fixed in the latest version. Please update.
