### ISSUE TITLE
Factions Error

### ISSUE THREAD

**Issue by mistakenCynic** [ProSavage/SavageFactions#245]
I have not made any modification to the plugin yet, however I seem to be getting the following error in the console. It repeats every minute or so. Any help would be much appreciated in resolving this. 

`[Factions]: Plugin Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6 generated an exception while executing task 45
Console 10/31/2019 21:43:44
21:43:44java.lang.IllegalStateException: FPlayerEnteredFactionEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[Paper-latest-2.jar:git-Paper-195]
at com.massivecraft.factions.listeners.FactionsPlayerListener.refreshPosition(FactionsPlayerListener.java:637) ~[?:?]
at com.massivecraft.factions.listeners.FactionsPlayerListener.lambda$startPositionCheck$4(FactionsPlayerListener.java:565) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-latest-2.jar:git-Paper-195]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[Paper-latest-2.jar:git-Paper-195]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper-latest-2.jar:git-Paper-195]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**Server VErsion (please complete the following information):**
 - Spigot Version: Paper 1.14.4
 - Factions Version: v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6

**Comment by prosavage** [comment]
I pushed https://github.com/illyria-io/illyriaFactions/commit/76be2c9aed35c8f34643bbbd098df81121f557b2 It should fix this. 

Grab a new build from the store; https://store.illyria.io
