### ISSUE TITLE
Faction fly issue

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#252]
Faction fly issue:
`[09:08:52 WARN]: [Factions] Plugin Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9 generated an exception while executing task 442
java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:709) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:688) ~[patched_1.13.2.jar:git-Paper-652]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:475) ~[?:?]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:466) ~[?:?]
at com.massivecraft.factions.zcore.persist.MemoryFPlayer.sendFancyMessage(MemoryFPlayer.java:1023) ~[?:?]
at com.massivecraft.factions.listeners.FactionsPlayerListener.refreshPosition(FactionsPlayerListener.java:705) ~[?:?]
at com.massivecraft.factions.listeners.FactionsPlayerListener.lambda$startPositionCheck$4(FactionsPlayerListener.java:564) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-652]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-652]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by SvenjaReissaus** [comment]
Take a look at our latest release from the [store](https://store.illyria.io)
