### ISSUE TITLE
Not a JSON Object: "Spawners"

### ISSUE THREAD

**Issue by sandor111** [ProSavage/SavageFactions#257]
https://pastebin.com/pVhz5iQ5
Resetting config didn't work issue started happening after updating from a version (5 days ago) to todays latest version.

**Comment by Keeeeezay** [comment]
@sandor111 Did you edit factions.json file? That is probably why it is throwing that error.

**Comment by sandor111** [comment]
> @sandor111 Did you edit factions.json file? That is probably why it is throwing that error.

No I did not, if I did it would have given the error on previous version as well but this issue started after I updated to the latest dev build.

**Comment by sandor111** [comment]
`  "12": {
    "rules": {},
    "tnt": 0,
    "upgrades": {
      "Spawners": 1
    },
    "id": "12",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "Hydra",
    "description": "Hydra",
    "open": false,
    "peaceful": false,
    "home": {
      "world": "world",
      "x": -9975.607366790231,
      "y": 3.0,
      "z": -2759.901909469989,
      "yaw": 178.7364501953125,
      "pitch": 1.549368977546692
    },
    "foundedDate": 1573930950725,`
That's in the factions.json file, when I remove this:
`"Spawners": 1`
It gives this error:
`[18:42:38 ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9 (Is it up to date?)
com.massivecraft.factions.shade.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "Crops"
at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]
at com.massivecraft.factions.zcore.persist.json.JSONFactions.loadCore(JSONFactions.java:83) ~[?:?]
at com.massivecraft.factions.zcore.persist.json.JSONFactions.load(JSONFactions.java:63) ~[?:?]
at com.massivecraft.factions.SavageFactions.onEnable(SavageFactions.java:168) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-652]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-652]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-652]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-652]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-652]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-652]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: Not a JSON Object: "Crops"
at com.massivecraft.factions.shade.com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
at com.massivecraft.factions.util.UpgradeAdapter.deserialize(UpgradeAdapter.java:14) ~[?:?]
at com.massivecraft.factions.util.UpgradeAdapter.deserialize(UpgradeAdapter.java:10) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]
... 20 more
[18:42:38 INFO]: [Factions] Disabling Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9`

**Comment by Keeeeezay** [comment]
Made some checks more secure. 5fec764
Update to latest build and let me know if it works.
