### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by Straikerinos** [ProSavage/SavageFactions#271]
**Describe the bug**
`Caused by: java.lang.IllegalStateException: Not a JSON Object: "Power"
at com.massivecraft.factions.shade.com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
at com.massivecraft.factions.util.UpgradeAdapter.deserialize(UpgradeAdapter.java:14) ~[?:?]
at com.massivecraft.factions.util.UpgradeAdapter.deserialize(UpgradeAdapter.java:10) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]
at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]
... 18 more`

**Server Version (please complete the following information):**
 - Spigot Version: git-Paper-225 (MC: 1.14.4)
 - Factions Version v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9
 - Minecraft Version: 1.14.4

**Comment by Drc-DEV** [comment]
Something's wrong in your data, regenerate the folder
