### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by FyFou57** [ProSavage/SavageFactions#273]
**Describe the bug**
No bug, just an error. I don't know why the bug is here, not how we can reproduce him, but he is hard spam in the log

> [05:45:57 ERROR]: Could not pass event PlayerInteractEvent to Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-9
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:748) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot-1.15.1.jar:git-PaperSpigot-4c7641d1]
... 18 more

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8
 - Factions Version http://prntscr.com/rs06w8

**Comment by Drc-DEV** [comment]
https://github.com/SavageLabs/SavageFactions/commit/dd7c17bb0bb05c47aa4590f9244fd555f8fc0857
