### ISSUE TITLE
/f perm not working for buttons, repeaters, tntfill

### ISSUE THREAD

**Issue by RogerPlaysMC** [ProSavage/SavageFactions#66]
**Describe the bug**
Non-faction members (enemy, neutral, etc.) are able to use buttons, repeaters, /tntfill in enemy territory, even with /f perm set to deny for those relations

**To Reproduce**

1. Create a faction and set /f perm for button to deny for enemy
2. Have someone from an enemy faction use a button (either stone or wood) in your territory
3. The button sends a redstone signal, and no message about the action not being allowed is passed to the player
4. No console errors

**Expected behavior**
It would be expected that enemies can't use buttons in your territory when when fperm -> enemy -> buttons is set to "deny".

**Screenshots**
Not needed, it wouldn't show much.

**Server VErsion (please complete the following information):**
 - Spigot Version: BeerSpigot (1.8.8 cannoning and pvp jar)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.4-STABLE
 - Minecraft Version: Version independant

**Additional context**
Fully explained above.

**Comment by RogerPlaysMC** [comment]
Repeaters also seem to ignore /f perms

Edit: Also /f perms for /tntfill are broken, so even with everything set to deny, if you are building a cannon someone can come in, /tntfill 1, and hit the button before the cannon is done, blowing the whole thing up. And you can change peoples tick rates on repeaters.

**Comment by prosavage** [comment]
Are you running an alpha build from Jenkins

**Comment by RogerPlaysMC** [comment]
No, v1.6.9.5-U0.2.1-RC-1.4-STABLE

**Comment by prosavage** [comment]
I want you to try resetting config & grab the latest job from Jenkins. https://jenkins.prosavage.net/

**Comment by prosavage** [comment]
Also you can add the button to territory protected materials in conf

**Comment by RogerPlaysMC** [comment]
Config was removed, new jar added, server restarted.

Still broken on all issues. Setting buttons in protected materials did prevent the use of them, but it ignores the permission, so if you want enemies to use them it still blocks it.  Without having it in the protected materials it ignores /f perm.  Tnt fill still bypasses the /f perm, as does setting enemies repeaters.

Adding levers to the list of things not following /f perms. Plus still getting the NPE, but from a new location.
`08.12 13:18:59 [Server] INFO Caused by: java.lang.NullPointerException
08.12 13:18:59 [Server] INFO at com.massivecraft.factions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:315) ~[Factions.jar:?]
08.12 13:18:59 [Server] INFO at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:816) ~[Factions.jar:?]
08.12 13:18:59 [Server] INFO at sun.reflect.GeneratedMethodAccessor298.invoke(Unknown Source) ~[?:?]
08.12 13:18:59 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
08.12 13:18:59 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
08.12 13:18:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
08.12 13:18:59 [Server] INFO ... 18 more`

**Comment by RogerPlaysMC** [comment]
For reference, I added the following code to another one of my core plugins to fix the permissions issue.

`
public class FactionPermOverrides implements Listener {

    @EventHandler(ignoreCancelled = true, priority = HIGH)
    public void onTileUse(PlayerInteractEvent event){
        Material type = event.getClickedBlock().getType();
        Location loc = event.getClickedBlock().getLocation();
        FLocation floc = new FLocation(loc);
        FPlayer fp = FPlayers.getInstance().getByPlayer(event.getPlayer());
        Faction faction = Board.getInstance().getFactionAt(floc);
        if(faction.isWilderness()||faction.isWarZone()||faction.isSafeZone()||fp.isAdminBypassing()){return;}
        if(fp.getFaction() == faction && fp.getRole() == Role.LEADER){return;}
        if(type == Material.WOOD_BUTTON || type == Material.STONE_BUTTON){
            if(faction.getAccess(fp, PermissableAction.BUTTON) == Access.ALLOW){
                return;}
            if(faction.getAccess(fp, PermissableAction.BUTTON) == Access.UNDEFINED || faction.getAccess(fp, PermissableAction.BUTTON) == Access.DENY){
                event.setCancelled(true);
                fp.sendMessage(ChatColor.RED + "You cannot use buttons without the proper permissions in this land.");
                return;}
        }
        if(type == Material.LEVER){
            if(faction.getAccess(fp, PermissableAction.LEVER) == Access.ALLOW){
                return;}
            if(faction.getAccess(fp, PermissableAction.LEVER) == Access.UNDEFINED || faction.getAccess(fp, PermissableAction.LEVER) == Access.DENY){
                event.setCancelled(true);
                fp.sendMessage(ChatColor.RED + "You cannot use levers without the proper permissions in this land.");
                return;}
        }
        if(type == Material.REDSTONE_COMPARATOR ||
                type == Material.DIODE ||
                type == Material.REDSTONE_COMPARATOR_OFF ||
                type == Material.REDSTONE_COMPARATOR_ON ||
                type == Material.DIODE_BLOCK_OFF ||
                type == Material.DIODE_BLOCK_ON){
            if(faction.getAccess(fp, PermissableAction.BUILD) == Access.ALLOW){
                return;}
            if(faction.getAccess(fp, PermissableAction.BUILD) == Access.UNDEFINED || faction.getAccess(fp, PermissableAction.BUILD) == Access.DENY){
                event.setCancelled(true);
                fp.sendMessage(ChatColor.RED + "You cannot use redstone machines without the proper permissions in this land.");
                return;}
        }
    }
}
`

**Comment by chilybones222** [comment]
Has there been a patch for this? I'm experiencing this currently on my server
`[20:53:59] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Factions v1.6.9.5-U0.2.1-RC-1.5-BETA
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e8ded36-acbc348]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-e8ded36-acbc348]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:315) ~[Factions.jar:?]
at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:816) ~[Factions.jar:?]
at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
... 17 more
[20:54:00] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Factions v1.6.9.5-U0.2.1-RC-1.5-BETA
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e8ded36-acbc348]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-e8ded36-acbc348]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:315) ~[Factions.jar:?]
at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:816) ~[Factions.jar:?]
at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
... 17 more`

**Comment by RogerPlaysMC** [comment]
I’m actually redoing the code for this section and submitting it this weekend, after that ProSavage will need to review it and we should be good to go. 

In the meantime you can add the code I posted to any one of your plugins (or if you don’t code have your dev do it). It’s a bandaid fix, but it will okay until the next version comes out.

**Comment by volitank** [comment]
Not sure if it's the same issue but it seems like this is happening for doors too on my server. I've tried the latest Factions-2018-12-29--07-51.jar and Factions-2018-12-24--00-21.jar

It's not doing any console error things though. They Perms Gui is accessible, it just seems like it's not doing anything.

**Comment by prosavage** [comment]
we fixed this recently.

**Comment by RogerPlaysMC** [comment]
I just tested, this was never actually fixed. You can still use buttons, repeaters, etc. in enemy land. Using the most recent version (built from github today).

**Comment by RogerPlaysMC** [comment]
I think it initially comes down to line 327 of the PlayerListener class.
`if (otherFaction.hasPlayersOnline()) {
            if (!Conf.territoryProtectedMaterials.contains(material))
                return true;
        } else {
            if (!Conf.territoryProtectedMaterialsWhenOffline.contains(material))
                return true;
        }`
So if the other faction has a player online and the material is not in protected materials, it returns true without ever checking access, relations, etc. Then if they are not online, same deal, it checks for protected materials, if not on the list, just returns true.
